resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - ingress.yaml
  - hpa-backend.yaml
  - hpa-frontend.yaml